activemodel・activesupportのバージョンアップデート
idcf/idcf-json_hyper_schema pull request #4
Opened 2020-05-26 07:29 UTC by yukihirop

## 概要

Fix idcf-private/issues#2416

`idcf-internal/idcfcloud-cli` の activesupportのバージョンを上げる必要が出たが、依存にこのライブラリがあったのでまずこちらのactivesupport(activemodel)のバージョンを上げた。

##  関連しているPR

https://github.com/idcf-internal/idcfcloud-cli/pull/29

このPRがマージされ、リリースしたら上記ライブラリの依存を更新する必要があります。

## 参考

こちらの記事を参考にruby2.7系でワーニングが出ないバージョンまで上げたつもりである。
https://tech.recruit-mp.co.jp/server-side/post-19932/

## レビュワーへ

- [ ] コードレビューをお願いします。

2020-05-26 07:31 UTC, yukihirop commented
## be rspec

```
Finished in 0.88085 seconds (files took 0.65451 seconds to load)
168 examples, 2 failures

Failed examples:

rspec './spec/idcf/json_hyper_schema/expands/base_spec.rb[1:15]' # idcf/json_hyper_schema/expands/base do!_url
rspec './spec/idcf/json_hyper_schema/expands/base_spec.rb[1:16]' # idcf/json_hyper_schema/expands/base do!_all
```

2020-05-26 07:37 UTC, yukihirop commented
@tkiminami さん

こっちもレビューしてもらえると助かります。
(アサインできなかったんですよね？何故だろうか....)

https://github.com/idcf/idcf-faraday_middleware/pull/3

2020-05-26 08:29 UTC, tkiminami requested changes
ライブラリ動作としては大丈夫そうです
rpspecに関しては
```
/spec/idcf/data/expand/url_before.json
```
のファイルが読み込めてないっぽいですね…

あとはREADME.mdにruby最低バージョン記載がありますので修正をお願いします

2020-05-29 01:36 UTC, yukihirop commented
@tkiminami 

これrubyの最低バージョンですがこちらは2.2.7からサポートなのに

idcf/idcf-faraday_middleware

こっちは1.9系からサポートしたいといっているのですが。。。。

![image](https://user-images.githubusercontent.com/11146767/83211497-34228580-a198-11ea-912d-98a241ea1389.png)

どちらを信用すればいいでしょうか？

2020-05-29 02:00 UTC, closed without merging